blank_issues_enabled: false
contact_links:
  - name: Booth
    url: https://raccoon-tail.booth.pm/
    about: ここに載っている説明・注意事項も合わせてご確認ください。
  - name: X(Twitter)
    url: https://x.com/RacoonT45037
    about: 緊急の連絡や個別相談が必要な場合はこちらから
